### ISSUE TITLE
Whitespace-dependent bug: "Assertion unknown might not hold"

### ISSUE THREAD

**Issue by nicoberling** [viperproject/gobra#418] opened 2022-02-22 14:38 UTC
Depending on the amount of empty lines after `package termination`, the test case `termination-fail-02.gobra` fails with the following message:

`<.:0:0> Postcondition might not hold. Assertion unknown might not hold.`
 
There does not seem to be a simple pattern (odd, even, ...) to predict whether it will fail with a given amount of empty lines. Below is the minimal code to duplicate this: It fails with 0,1 or 2 empty lines, succeeds with 3 and then fails again with 4. The same behaviour can be seen when parsing with ANTLR ( #388 ),  but for different numbers of empty lines.

```
// Any copyright is dedicated to the Public Domain.
// http://creativecommons.org/publicdomain/zero/1.0/

package termination

type Func interface {
	pure
	decreases n
	fun(n int, a Func) int
}

type FuncImpl struct {}

(FuncImpl) implements Func {
	pure (f FuncImpl) fun (n int, a Func) int {
		//:: ExpectedOutput(pure_function_termination_error)
		return f.fun(n, a)
	}
}

pure
decreases n
func (f FuncImpl) fun (n int, a Func) int {
	//:: ExpectedOutput(pure_function_termination_error)
	return n * a.fun(n, f)
}
```

**Comment by jcp19** [comment] 2022-02-22 15:22
Is this really dependent on the number of empty lines? Did you try multiple times with the same number of empty lines until you get a different result from before? This might be a non-deterministic issue

**Comment by jogasser** [comment] 2022-03-07 10:48
I encountered the same bug when working on the uniqueness of viper member names: 
Again adding a very specific amount of whitespaces fixes the error.

You may find the two files here: [termination_error.zip](https://github.com/viperproject/gobra/files/8196971/termination_error.zip)

termination-error.gobra.vpr contains the viper code that causes the error
termination-noerror.gobra.vpr contains the viper code where the error doesn't happend (I had to add 6 white spaces after the package clause)



The Gobra output for the correctly working version:
```
[info] Gobra has found 4 error(s) in package src/test/resources/regressions/features/termination - termination
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:34:11> Function might not terminate.
[info] Required tuple condition might not hold.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:34:11> Function might not terminate.
[info] Required tuple condition might not hold.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:34:11> Function might not terminate.
[info] Required tuple condition might not hold.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:34:11> Function might not terminate.
[info] Required tuple condition might not hold.
```

The Gobra output for the faulty version:
```
[info] Gobra has found 5 error(s) in package src/test/resources/regressions/features/termination - termination
[info]     <.:0:0> Postcondition might not hold.
[info] Assertion unknown might not hold.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:28:11> Function might not terminate.
[info] Termination measure might not decrease or might not be bounded.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:44:11> Function might not terminate.
[info] Termination measure might not decrease or might not be bounded.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:70:10> Pure function might not terminate.
[info] Termination measure might not decrease or might not be bounded.
[info]     <src/test/resources/regressions/features/termination/termination-fail-02.gobra:78:13> Pure function might not terminate.
[info] Required tuple condition might not hold.
```

Note that there isn't just an additional error outputted, but the error messages seem to differ too.

For me, the unexpected viper error happens on line 331, where the postcondition fails. It is marked at position 0:0 in Gobra because the backtracking information is missing since the corresponding viper code is generated from an interface implementation where the related functions seem to get put into a single function.

**Comment by jcp19** [comment] 2022-03-09 14:17
Boogie seems to have suffered from similar issues \[[PR 452](https://github.com/boogie-org/boogie/pull/452), [PR 454](https://github.com/boogie-org/boogie/pull/454)\]. In essence, the root cause seems to be that the behavior of SMT solvers can vary (in terms of runtime and output) when identifiers in the input are renamed. Thus, when we make changes that may affect the identifiers generated by Gobra at the SMT level, we can observe different behaviors. [This comment](https://github.com/boogie-org/boogie/pull/452#issuecomment-968367114) in one of the aforementioned issues might give us some ideas on how to address this problem in Gobra.

Thanks @gauravpartha for making me aware that Boogie also suffered from this and for sharing the links!

**Comment by ArquintL** [comment] 2022-03-09 16:18
@jcp19 Might this be fixed by the latest Z3 release we're currently discussing in Viper? Would be a nice additional argument for upgrading

**Comment by jcp19** [comment] 2022-03-09 16:20
> @jcp19 Might this be fixed by the latest Z3 release we're currently discussing in Viper? Would be a nice additional argument for upgrading

I had the same idea. I plan to test this soon.

**Comment by jcp19** [comment] 2022-03-09 16:51
The reason why this bug has only been found so far in combination with termination measures in interfaces has to do with the fact that the viper members originated from implementation proofs still use the line numbers of the interface definition in their name. This is probably one of the few places where the encoding of a member is not yet resilient to unrelated changes in the same input file.

**Comment by Felalolf** [comment] 2022-05-18 13:53
The problems described in this issue has been solved. This particular file has separate issues that are covered in this PR #450 and issue #451.

**Closed by Felalolf** 2022-05-18 13:53 UTC
